## NumPy array and basic

In [24]:
import numpy as np
import time

In [25]:
arr_1d = np.array([1,2,3,4,5])
print("1D arr: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("1D arr: ", arr_2d)

1D arr:  [1 2 3 4 5]
1D arr:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [26]:
py_list = [1,2,3]
print("multiply by 2", py_list*2)

np_list = np.array([1,2,3])
print("multiply by 2", np_list*2)

multiply by 2 [1, 2, 3, 1, 2, 3]
multiply by 2 [2 4 6]


In [35]:
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:", time.time()- start)


 List operation time: 0.08977174758911133


In [36]:
start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time:", time.time()- start)


 Numpy operation time: 0.0022330284118652344


### create array from scratch

In [42]:
zero = np.zeros((3,4))
print("zeros : \n", zero)

ones = np.ones((2,2))
print("ones : \n", ones)

full = np.full((2,2),2)
print("ones : \n", full)


zeros : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones : 
 [[1. 1.]
 [1. 1.]]
ones : 
 [[2 2]
 [2 2]]
