### Advance operation with Business example (source .venv/bin/activate)

In [9]:
import numpy as np
import matplotlib.pyplot as plt

In [23]:
# Data sturcture: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 15000, 18000, 21000, 10000], #rest1
    [2, 12000, 13000, 14000, 16000], #rest2
    [3, 20000, 22000, 24000, 28000], #rest3
    [4, 17000, 19000, 20000, 23000], #rest4
    [5, 13000, 15000, 16000, 18000]  #rest5
])

print("=== Sales anlysis====")
print("Sample data for 1st 3 restaurant:", sales_data[0:3])
# print("Sample data for 1st 3 restaurant:", sales_data[:,1:])

=== Sales anlysis====
Sample data for 1st 3 restaurant: [[    1 15000 18000 21000 10000]
 [    2 12000 13000 14000 16000]
 [    3 20000 22000 24000 28000]]


In [29]:
# Total sales per years

# print(np.sum(sales_data, axis=0)) #sum of each year
print(np.sum(sales_data[:,1:], axis=0)) #sum of each year

# Minimum sales per year
min_sales = np.min(sales_data[:,1:], axis=1)
print(min_sales)

# Maximum sales per year
max_sales = np.max(sales_data[:,1:], axis=0)
print(max_sales)

[77000 87000 95000 95000]
[10000 12000 20000 17000 13000]
[20000 22000 24000 28000]
