## NumPy array and basic

In [2]:
import numpy as np
import time

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D arr: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("1D arr: ", arr_2d)

1D arr:  [1 2 3 4 5]
1D arr:  [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [4]:
py_list = [1,2,3]
print("multiply by 2", py_list*2)

np_list = np.array([1,2,3])
print("multiply by 2", np_list*2)

multiply by 2 [1, 2, 3, 1, 2, 3]
multiply by 2 [2 4 6]


In [5]:
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:", time.time()- start)


 List operation time: 0.06749415397644043


In [6]:
start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time:", time.time()- start)


 Numpy operation time: 0.0036373138427734375


### create array from scratch

In [12]:
zero = np.zeros((3,4))
print("zeros : \n", zero)

ones = np.ones((2,2))
print("ones : \n", ones)

full = np.full((2,2),2)
print("ones : \n", full)

random = np.random.random((2,2))
print("ones : \n", random)

arr = np.arange(10)
print("arr: ", arr)

zeros : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones : 
 [[1. 1.]
 [1. 1.]]
ones : 
 [[2 2]
 [2 2]]
ones : 
 [[0.03506575 0.81655249]
 [0.36930769 0.05797448]]
arr:  [0 1 2 3 4 5 6 7 8 9]


### Vector, Matrix and Tensor

In [19]:
vector = np.array([1,2,3])
print("vector: ", vector)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor: \n", tensor)

vector:  [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array shape: ", arr.shape)
print("Array dimensions: ", arr.ndim)
print("Array size: ", arr.size)
print("Array data type: ", arr.dtype)

Array shape:  (2, 3)
Array dimensions:  2
Array size:  6
Array data type:  int64


### Array Reshaping

In [33]:
arr = np.arange(12)
print("Original array: \n", arr)

reshaped_arr = arr.reshape((3,4))
print("Reshaped array (3x4): \n", reshaped_arr)

flattend_arr = reshaped_arr.flatten()
print("Flattened array: \n", flattend_arr)

ravel_arr = reshaped_arr.ravel()
print("Raveled array: \n", ravel_arr)

tranpose = reshaped_arr.T
print("Transposed array: \n", tranpose)

Original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4): 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
