In [12]:
import numpy as np

### NumPy Array Operations

In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9])
# arr = np.arange(10)
print("array slice:",arr[2:7])
print("array step", arr[1:8:2])
print("array indexing:", arr[-6:-2])
print("array indexing:", arr[-3])


array slice: [3 4 5 6 7]
array step [2 4 6 8]
array indexing: [4 5 6 7]
array indexing: 7


In [14]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("specific element:", arr_2d[1,2]) 
print("entire row:", arr_2d[1])
print("entire row:", arr_2d[:, 2])

specific element: 6
entire row: [4 5 6]
entire row: [3 6 9]


In [15]:
unsorted_arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
sorted_arr = np.sort(unsorted_arr)
print("Unsorted array:", unsorted_arr)
print("Sorted array:", sorted_arr)

arr_2d = np.array([[1,7],[1,4],[3,6]])
print("sorted 2d array:", np.sort(arr_2d, axis=0))  # Sort along columns

Unsorted array: [3 1 4 1 5 9 2 6 5]
Sorted array: [1 1 2 3 4 5 5 6 9]
sorted 2d array: [[1 4]
 [1 6]
 [3 7]]


### Filter

In [16]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = numbers[numbers % 2 == 0]
odd_num = numbers[numbers % 2 == 1]
print(even_num)
print(odd_num)

[ 2  4  6  8 10]
[1 3 5 7 9]


### Filter with mask

In [17]:
mask = numbers > 5
print(mask)
print("Mask:", numbers[mask])

[False False False False False  True  True  True  True  True]
Mask: [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [18]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("Where result:", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Where result: [ 6  7  8  9 10]


In [21]:
condition_array = np.where(numbers > 5,numbers*2,numbers)
print("Condition array:", condition_array)

Condition array: [ 1  2  3  4  5 12 14 16 18 20]


### Adding and Removing Array

In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# condition_array = arr1 + arr2
condition_array = np.concatenate((arr1, arr2))
print("Added array:", condition_array)

Added array: [1 2 3 4 5 6]


### Array Compatibility

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print("Are a and b compatible?", a.shape == b.shape)
print("Are b and c compatible?", b.shape == c.shape)

Are a and b compatible? True
Are b and c compatible? False


In [31]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original,new_row))

# print(original)
# print(with_new_row)


new_col = np.array([[5],[6]])

with_new_col = np.hstack((original,new_col))

print(original)
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2 5]
 [3 4 6]]


### Array Delete

In [33]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5 6]
